import { LegalPageLayout, LegalP, LegalList, type LegalSection } from "@/components/legal-page-layout";

/* ------------------------------------------------------------------------
   Placeholder legal copy — this is UI scaffolding, not legal advice. Have
   an actual lawyer review and replace this text (and confirm your real
   legal basis / retention periods / sub-processors) before shipping to
   real users. Update the contact email at the bottom before launch.
------------------------------------------------------------------------- */

const SECTIONS: LegalSection[] = [
  {
    id: "overview",
    heading: "1. Overview",
    content: (
      <LegalP>
        This policy explains what information Trackly collects, why we collect it, and what rights you have
        over it. Trackly was built around a simple idea — you shouldn&apos;t have to accept opaque data
        practices from a job tracker while it&apos;s helping you flag opaque data practices everywhere else.
      </LegalP>
    ),
  },
  {
    id: "information-we-collect",
    heading: "2. Information We Collect",
    content: (
      <>
        <LegalP>We collect information in two ways:</LegalP>
        <LegalList
          items={[
            "Information you give us directly — your email, and any job, company, or note details you add.",
            "Information generated by the service — scan results, privacy scores, and activity like status changes and reminders.",
          ]}
        />
        <LegalP>We don&apos;t use ad trackers or analytics that follow you across other sites.</LegalP>
      </>
    ),
  },
  {
    id: "how-we-use-your-information",
    heading: "3. How We Use Your Information",
    content: (
      <LegalList
        items={[
          "To operate your dashboard, job board, and reminders.",
          "To run privacy scans against the companies you apply to.",
          "To maintain the security and integrity of the service.",
          "To communicate with you about your account, if you contact us first.",
        ]}
      />
    ),
  },
  {
    id: "legal-basis-for-processing",
    heading: "4. Legal Basis for Processing (GDPR)",
    content: (
      <LegalP>
        Where GDPR applies, we process your account and job data under contract (to provide the service you
        signed up for) and process limited technical data under legitimate interest (to keep the service
        secure and working correctly).
      </LegalP>
    ),
  },
  {
    id: "how-the-privacy-scanning-feature-works",
    heading: "5. How the Privacy Scanning Feature Works",
    content: (
      <LegalP>
        When you add a job, Trackly automatically looks for that company&apos;s published privacy policy and
        extracts structured details — retention periods, contact emails, and whether third-party sharing is
        mentioned. This only reads publicly available pages (respecting robots.txt) and never submits your
        personal data to the company being scanned.
      </LegalP>
    ),
  },
  {
    id: "data-sharing-and-third-parties",
    heading: "6. Data Sharing & Third Parties",
    content: (
      <>
        <LegalP>We don&apos;t sell your data, and we don&apos;t share it for advertising purposes. Ever.</LegalP>
        <LegalP>
          We use a small number of infrastructure providers (such as our hosting and database provider)
          strictly to run the service — they process data on our behalf under their own data-processing
          agreements, not for their own purposes.
        </LegalP>
      </>
    ),
  },
  {
    id: "data-retention",
    heading: "7. Data Retention",
    content: (
      <LegalP>
        We keep your account and job data for as long as your account is active. Scanned privacy-policy
        documents are cached and refreshed periodically so results stay current. Deleting your account
        deletes your personal data; company-level scan data (which isn&apos;t tied to you individually) may be
        retained to avoid re-scanning the same public page for other users.
      </LegalP>
    ),
  },
  {
    id: "your-rights",
    heading: "8. Your Rights",
    content: (
      <>
        <LegalP>Depending on where you live, you may have the right to:</LegalP>
        <LegalList
          items={[
            "Access the personal data we hold about you.",
            "Correct inaccurate data.",
            "Request deletion of your data.",
            "Export your data in a portable format.",
            "Object to or restrict certain processing.",
          ]}
        />
        <LegalP>You can exercise most of these directly from your account settings, or by contacting us below.</LegalP>
      </>
    ),
  },
  {
    id: "cookies-and-tracking",
    heading: "9. Cookies & Tracking",
    content: (
      <LegalP>
        We use only the strictly necessary cookies required to keep you signed in. No advertising or
        cross-site tracking cookies are used.
      </LegalP>
    ),
  },
  {
    id: "data-security",
    heading: "10. Data Security",
    content: (
      <LegalP>
        We use industry-standard practices — encrypted connections, access controls, and row-level security
        on our database — to protect your data. No system is perfectly secure, but we treat your data with
        the same scrutiny this product asks of everyone else.
      </LegalP>
    ),
  },
  {
    id: "childrens-privacy",
    heading: "11. Children's Privacy",
    content: (
      <LegalP>
        Trackly isn&apos;t directed at children, and we don&apos;t knowingly collect data from anyone under 16.
      </LegalP>
    ),
  },
  {
    id: "international-data-transfers",
    heading: "12. International Data Transfers",
    content: (
      <LegalP>
        If you&apos;re accessing Trackly from outside the region where our servers are hosted, your data may
        be transferred internationally. Where required, we rely on appropriate safeguards for those transfers.
      </LegalP>
    ),
  },
  {
    id: "changes-to-this-policy",
    heading: "13. Changes to This Policy",
    content: (
      <LegalP>
        If we make material changes to this policy, we&apos;ll notify you before they take effect. The &quot;last
        updated&quot; date at the top always reflects the current version.
      </LegalP>
    ),
  },
  {
    id: "contact-us",
    heading: "14. Contact Us",
    content: (
      <LegalP>
        Questions about this policy or your data? Reach out at{" "}
        <a href="mailto:privacy@trackly.app" className="text-gray-900 underline underline-offset-2 hover:text-red-600">
          privacy@trackly.app
        </a>
        .
      </LegalP>
    ),
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPageLayout
      eyebrow="Legal"
      title="Privacy Policy"
      lastUpdated="August 11, 2026"
      sections={SECTIONS}
    />
  );
}