import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import "../globals.css";
import Footer from "@/components/footer";
import SmoothScroll from "@/components/smooth-scroll";

export const metadata: Metadata = {
  title: "trackly",
  description: "Generated by create next app",
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <SmoothScroll>
        <Navbar />
        {children}
        <Footer />
      </SmoothScroll>
    </div>
  );
}
