import type { Metadata } from "next";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "react-hot-toast";
import { GlobalCommandPalette } from "@/components/GlobalCommandPalette";

export const metadata: Metadata = {
  title: "trackly | dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <GlobalCommandPalette />
      <SidebarProvider>
        <AppSidebar />
        <main className="flex w-full min-w-0 flex-1 flex-col">{children}</main>
      </SidebarProvider>
      <Toaster position="top-right" reverseOrder={false} />
    </ThemeProvider>
  );
}
